### ISSUE TITLE
error in installing package

### ISSUE THREAD

**Issue by MaryamMghz** [AkchurinDA/Fortuna.jl#96]
Hi 
I am trying to use Fortuna but I have issues in installing this package. The error is included
Precompiling packages...
           ✗ SimpleNonlinearSolve
           ✗ SimpleNonlinearSolve → SimpleNonlinearSolveChainRulesCoreExt
           ✗ NonlinearSolve
           ✗ Fortuna
  0 dependencies successfully precompiled in 9 seconds. 205 already precompiled.
  4 dependencies errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

**Comment by akchurinda** [comment]
Hi @MaryamMghz,

Thank you for the report of the error! I saw it this morning as well. Please let me look into it tonight and I will get back to this issue ASAP.

Thank you for using `Fortuna.jl`!

**Comment by akchurinda** [comment]
Hi @MaryamMghz,

I’ve just published a new version of the package (v0.10.2), which addresses the issue with `NonlinearSolve.jl` not compiling - at least, I haven't encountered the problem again.

To update, please remove the existing version of the package using `rm Fortuna` and install the newly registered version with `add Fortuna`. If the old version still gets installed, you can force an update by running `up Fortuna`.

Let me know if the issue persists. Thanks again for reporting it!

**Comment by MaryamMghz** [comment]
Hi @AkchurinDA 
Thank you for your response. I am still having the same issue with new version.
   Updating registry at `C:\Users\marya\.julia\registries\General.toml`
  No Changes to `C:\Users\marya\.julia\environments\v1.10\Project.toml`
  No Changes to `C:\Users\marya\.julia\environments\v1.10\Manifest.toml`
Precompiling packages...
           ✗ SimpleNonlinearSolve
           ✗ SimpleNonlinearSolve → SimpleNonlinearSolveChainRulesCoreExt
           ✗ NonlinearSolve
           ✗ SimpleNonlinearSolve → SimpleNonlinearSolveReverseDiffExt
           ✗ Fortuna
  0 dependencies successfully precompiled in 12 seconds. 210 already precompiled.
  5 dependencies errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`
Thank you

**Comment by akchurinda** [comment]
@MaryamMghz,

There seems to be a problem with the current version of the `NonlinearSolve.jl`, which is a major dependency of `Fortuna.jl`. Let me dig into it over the weekend and I will get back to you as soon as I have any updates. 

For now, I will keep this issue open. Thank you for patience.

**Comment by akchurinda** [comment]
Hi @MaryamMghz,

The precompilation error with `NonlinearSolve.jl` in this [issue](https://github.com/SciML/NonlinearSolve.jl/issues/519) was fixed with this [PR](https://github.com/SciML/NonlinearSolve.jl/pull/520). Everything should work properly now.

Thanks again for pointing this out. Please feel free to reach out to me directly if you have any questions regarding `Fortuna.jl`!
